name: flutter_utils
description: "Flutter / Dart Utility Project"
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '^3.6.0'
dependencies:
  flutter:
    sdk: flutter
  get_thumbnail_video: ^0.7.3
  fc_native_image_resize: ^0.14.2
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.1
  get_time_ago: ^2.1.1
  flutter_cache_manager: any
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  photo_view: ^0.15.0
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/notfound.jpg
    - assets/images/folder.jpg
    - assets/images/file.jpg
