name: flutter_utils
description: "Flutter / Dart Utility Project"
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  video_thumbnail: ^0.5.3
  fc_native_image_resize: ^0.7.0
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.1
  get_time_ago: ^1.3.1
  flutter_cache_manager: any
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  uuid: ^4.3.3
  photo_view: ^0.14.0
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/notfound.jpg
    - assets/images/folder.jpg
    - assets/images/file.jpg
